// default package
// Generated Sep 17, 2016 3:06:32 PM by Hibernate Tools 4.3.1.Final

package com.musiccamp.entities;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Electives generated by hbm2java
 */
@Entity
@Table(name = "electives", catalog = "music_maestros")
public class Electives implements java.io.Serializable {

	private Integer electiveId;
	private String electiveName;
	private Set<RoomTimings> roomTimingses = new HashSet<RoomTimings>(0);

	public Electives() {
	}

	public Electives(String electiveName, Set<RoomTimings> roomTimingses) {
		this.electiveName = electiveName;
		this.roomTimingses = roomTimingses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "elective_id", unique = true, nullable = false)
	public Integer getElectiveId() {
		return this.electiveId;
	}

	public void setElectiveId(Integer electiveId) {
		this.electiveId = electiveId;
	}

	@Column(name = "elective_name")
	public String getElectiveName() {
		return this.electiveName;
	}

	public void setElectiveName(String electiveName) {
		this.electiveName = electiveName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "electives")
	public Set<RoomTimings> getRoomTimingses() {
		return this.roomTimingses;
	}

	public void setRoomTimingses(Set<RoomTimings> roomTimingses) {
		this.roomTimingses = roomTimingses;
	}

}
