package com.musiccamp.entities;
// Generated Oct 17, 2016 2:14:25 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Electives generated by hbm2java
 */
@Entity
@Table(name = "electives")
public class Electives implements java.io.Serializable {

	private Integer electiveId;
	private String electiveName;
	private Set<ElectiveRoomTimings> electiveRoomTimingses = new HashSet<ElectiveRoomTimings>(0);

	public Electives() {
	}

	public Electives(String electiveName, Set<ElectiveRoomTimings> electiveRoomTimingses) {
		this.electiveName = electiveName;
		this.electiveRoomTimingses = electiveRoomTimingses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "elective_id", unique = true, nullable = false)
	public Integer getElectiveId() {
		return this.electiveId;
	}

	public void setElectiveId(Integer electiveId) {
		this.electiveId = electiveId;
	}

	@Column(name = "elective_name")
	public String getElectiveName() {
		return this.electiveName;
	}

	public void setElectiveName(String electiveName) {
		this.electiveName = electiveName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "electives")
	public Set<ElectiveRoomTimings> getElectiveRoomTimingses() {
		return this.electiveRoomTimingses;
	}

	public void setElectiveRoomTimingses(Set<ElectiveRoomTimings> electiveRoomTimingses) {
		this.electiveRoomTimingses = electiveRoomTimingses;
	}

}
