// default package
// Generated Sep 17, 2016 3:06:32 PM by Hibernate Tools 4.3.1.Final

package com.musiccamp.entities;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RoomTimings generated by hbm2java
 */
@Entity
@Table(name = "room_timings", catalog = "music_maestros")
public class RoomTimings implements java.io.Serializable {

	private RoomTimingsId id;
	private Electives electives;
	private Room room;
	private Timings timings;
	private String roomNum;
	private String electiveName;
	private String timeSlot;

	public RoomTimings() {
	}

	public RoomTimings(RoomTimingsId id, Electives electives, Room room, Timings timings, String timeSlot) {
		this.id = id;
		this.electives = electives;
		this.room = room;
		this.timings = timings;
		this.timeSlot = timeSlot;
	}

	public RoomTimings(RoomTimingsId id, Electives electives, Room room, Timings timings, String roomNum,
			String electiveName, String timeSlot) {
		this.id = id;
		this.electives = electives;
		this.room = room;
		this.timings = timings;
		this.roomNum = roomNum;
		this.electiveName = electiveName;
		this.timeSlot = timeSlot;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "roomId", column = @Column(name = "roomID", nullable = false)),
			@AttributeOverride(name = "electiveId", column = @Column(name = "electiveID", nullable = false)),
			@AttributeOverride(name = "timeId", column = @Column(name = "timeID", nullable = false)) })
	public RoomTimingsId getId() {
		return this.id;
	}

	public void setId(RoomTimingsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "electiveID", nullable = false, insertable = false, updatable = false)
	public Electives getElectives() {
		return this.electives;
	}

	public void setElectives(Electives electives) {
		this.electives = electives;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roomID", nullable = false, insertable = false, updatable = false)
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "timeID", nullable = false, insertable = false, updatable = false)
	public Timings getTimings() {
		return this.timings;
	}

	public void setTimings(Timings timings) {
		this.timings = timings;
	}

	@Column(name = "roomNum")
	public String getRoomNum() {
		return this.roomNum;
	}

	public void setRoomNum(String roomNum) {
		this.roomNum = roomNum;
	}

	@Column(name = "electiveName")
	public String getElectiveName() {
		return this.electiveName;
	}

	public void setElectiveName(String electiveName) {
		this.electiveName = electiveName;
	}

	@Column(name = "timeSlot", nullable = false)
	public String getTimeSlot() {
		return this.timeSlot;
	}

	public void setTimeSlot(String timeSlot) {
		this.timeSlot = timeSlot;
	}

}
