package com.musiccamp.entities;
// Generated Sep 21, 2016 10:34:07 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RoomTimings generated by hbm2java
 */
@Entity
@Table(name = "room_timings", catalog = "music_maestros")
public class RoomTimings implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer rtId;
	private Room room;
	private Timings timings;
	private Set<ElectiveRoomTimings> electiveRoomTimingses = new HashSet<ElectiveRoomTimings>(0);

	public RoomTimings() {
	}

	public RoomTimings(Room room, Timings timings, Set<ElectiveRoomTimings> electiveRoomTimingses) {
		this.room = room;
		this.timings = timings;
		this.electiveRoomTimingses = electiveRoomTimingses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "rt_id", unique = true, nullable = false)
	public Integer getRtId() {
		return this.rtId;
	}

	public void setRtId(Integer rtId) {
		this.rtId = rtId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room_id")
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "time_id")
	public Timings getTimings() {
		return this.timings;
	}

	public void setTimings(Timings timings) {
		this.timings = timings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roomTimings")
	public Set<ElectiveRoomTimings> getElectiveRoomTimingses() {
		return this.electiveRoomTimingses;
	}

	public void setElectiveRoomTimingses(Set<ElectiveRoomTimings> electiveRoomTimingses) {
		this.electiveRoomTimingses = electiveRoomTimingses;
	}

//	@Override
//	public String toString() {
//		return  rtId.toString() + " " + room.toString() + " " +
//timings.toString() + " " + electiveRoomTimingses.toString();
//	}

	
}
