// default package
// Generated Sep 17, 2016 3:06:32 PM by Hibernate Tools 4.3.1.Final

package com.musiccamp.entities;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RoomTimingsId generated by hbm2java
 */
@Embeddable
public class RoomTimingsId implements java.io.Serializable {

	private int roomId;
	private int electiveId;
	private int timeId;

	public RoomTimingsId() {
	}

	public RoomTimingsId(int roomId, int electiveId, int timeId) {
		this.roomId = roomId;
		this.electiveId = electiveId;
		this.timeId = timeId;
	}

	@Column(name = "roomID", nullable = false)
	public int getRoomId() {
		return this.roomId;
	}

	public void setRoomId(int roomId) {
		this.roomId = roomId;
	}

	@Column(name = "electiveID", nullable = false)
	public int getElectiveId() {
		return this.electiveId;
	}

	public void setElectiveId(int electiveId) {
		this.electiveId = electiveId;
	}

	@Column(name = "timeID", nullable = false)
	public int getTimeId() {
		return this.timeId;
	}

	public void setTimeId(int timeId) {
		this.timeId = timeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoomTimingsId))
			return false;
		RoomTimingsId castOther = (RoomTimingsId) other;

		return (this.getRoomId() == castOther.getRoomId()) && (this.getElectiveId() == castOther.getElectiveId())
				&& (this.getTimeId() == castOther.getTimeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRoomId();
		result = 37 * result + this.getElectiveId();
		result = 37 * result + this.getTimeId();
		return result;
	}

}
