package com.musiccamp.entities;
// Generated Oct 17, 2016 2:14:25 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Timings generated by hbm2java
 */
@Entity
@Table(name = "timings", catalog = "music_maestros")
public class Timings implements java.io.Serializable {

	private Integer timeId;
	private String timeSlot;
	private Set<RoomTimings> roomTimingses = new HashSet<RoomTimings>(0);

	public Timings() {
	}

	public Timings(String timeSlot) {
		this.timeSlot = timeSlot;
	}

	public Timings(String timeSlot, Set<RoomTimings> roomTimingses) {
		this.timeSlot = timeSlot;
		this.roomTimingses = roomTimingses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "time_id", unique = true, nullable = false)
	public Integer getTimeId() {
		return this.timeId;
	}

	public void setTimeId(Integer timeId) {
		this.timeId = timeId;
	}

	@Column(name = "time_slot", nullable = false)
	public String getTimeSlot() {
		return this.timeSlot;
	}

	public void setTimeSlot(String timeSlot) {
		this.timeSlot = timeSlot;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "timings")
	public Set<RoomTimings> getRoomTimingses() {
		return this.roomTimingses;
	}

	public void setRoomTimingses(Set<RoomTimings> roomTimingses) {
		this.roomTimingses = roomTimingses;
	}

}
