package com.musiccamp.entities;
// Generated Oct 17, 2016 2:14:25 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserLogin generated by hbm2java
 */
@Entity
@Table(name = "user_login", catalog = "music_maestros")
public class UserLogin implements java.io.Serializable {

	private int username;
	private String password;
	private Integer role;

	public UserLogin() {
	}

	public UserLogin(int username) {
		this.username = username;
	}

	public UserLogin(int username, String password, Integer role) {
		this.username = username;
		this.password = password;
		this.role = role;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false)
	public int getUsername() {
		return this.username;
	}

	public void setUsername(int username) {
		this.username = username;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "role")
	public Integer getRole() {
		return this.role;
	}

	public void setRole(Integer role) {
		this.role = role;
	}

}
